micronaut:
    application:
        name: satloca
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**

nasa:
    tle-api:
        url: http://data.ivanstanojevic.me/api/tle

jackson:
    serialization:
        writeDatesAsTimestamps: false
    deserialization:
        readDatesAsTimestamps: false
    #property-naming-strategy: SNAKE_CASE
    #bean-introspection-module: true

datasources:
    default:
        url: ${JDBC_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
        dialect: ${JDBC_DIALECT:H2}

jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                    show_sql: true